SOLVER_TIMEOUT ?= 900

# Input files
DATA_DIR = data
RAW = $(DATA_DIR)/Train\ PTG\ cleaned.csv

GMPL = schedule.mod

# Input data files which are autogenerated
TRACKS = $(DATA_DIR)/tracks.csv
CONFLICTS = $(DATA_DIR)/conflicts.csv
CPLEX = schedule-cplex.lp

# Input data files which *will* be autogenerated when I write the code
# to do it, but need to be written manually for now.
DATA_DIR_EXISTS = $(DATA_DIR)/$(DIR_EXISTS)

GMPL_FILES = \
	$(GMPL) $(TRACKS) $(CONFLICTS)

# Output files
DIR_EXISTS = .dir-exists
OUTPUT_DIR = output
SOLUTIONS_DIR = $(OUTPUT_DIR)/solutions
REPORTS_DIR = $(OUTPUT_DIR)/reports
TIMINGS_DIR = $(OUTPUT_DIR)/timings
SOLUTIONS_DIR_EXISTS = $(SOLUTIONS_DIR)/$(DIR_EXISTS)
REPORTS_DIR_EXISTS = $(REPORTS_DIR)/$(DIR_EXISTS)
TIMINGS_DIR_EXISTS = $(TIMINGS_DIR)/$(DIR_EXISTS)

GLPSOL_TIMING = $(TIMINGS_DIR)/glpsol.txt
SCIP_TIMING = $(TIMINGS_DIR)/scip.txt
CBC_TIMING = $(TIMINGS_DIR)/cbc.txt

GLPSOL_SOLUTION = $(SOLUTIONS_DIR)/glpsol.txt
SCIP_SOLUTION = $(SOLUTIONS_DIR)/scip.txt
CBC_SOLUTION = $(SOLUTIONS_DIR)/cbc.txt

GLPSOL_REPORT = $(REPORTS_DIR)/glpsol.txt
SCIP_REPORT = $(REPORTS_DIR)/scip.txt
CBC_REPORT = $(REPORTS_DIR)/cbc.txt
REPORTS = $(GLPSOL_REPORT) $(SCIP_REPORT) $(CBC_REPORT)

# Solver arguments
GLPSOL_INPUTS = --math $(GMPL) # --data $(GMPL_...)
GLPSOL_SOLVE_OPTIONS = --tmlim $(SOLVER_TIMEOUT)
SCIP = ./scip
CBC = ./Cbc-2.9.8/build/Cbc/src/cbc
CBC_SOLVE_OPTIONS = sec $(SOLVER_TIMEOUT)

# Reporter arguments
REPORT_ARGS = $(TRACKS)

.PHONY: default
default: cbc

.PHONY: all
all: $(REPORTS)

prep:
	mkdir -p \
		$(DATA_DIR) \
		$(SOLUTIONS_DIR) $(TIMINGS_DIR) $(REPORTS_DIR)

$(TRACKS) $(CONFLICTS): $(RAW) extract_csv_data.py
	./extract_csv_data.py "$<" $(TRACKS) $(CONFLICTS)

compare: all
	@for report in $(REPORTS_DIR)/{lp_solve,glpsol,scip,cbc}.txt; do \
		echo; \
		awk '/^Solver:/,/CPU/ {print}' $$report; \
	done

compare-cbc-scip: $(CBC_REPORT) $(SCIP_REPORT)
	bash -c '\
	    bandx () { sed "s/\([a-z]\+\)[123]/\1X/g" "$$@"; }; \
	    dl --label cbc --label scip \
	    <(bandx $(CBC_REPORT)) \
	    <(bandx $(SCIP_REPORT))'

compare-cbc-glpsol: $(CBC_REPORT) $(GLPSOL_REPORT)
	bash -c '\
	    bandx () { sed "s/\([a-z]\+\)[123]/\1X/g" "$$@"; }; \
	    dl --label cbc --label glpsol \
	    <(bandx $(CBC_REPORT)) \
	    <(bandx $(GLPSOL_REPORT))'

compare-cbc-lp_solve: $(CBC_REPORT) $(LP_SOLVE_REPORT)
	bash -c '\
	    bandx () { sed "s/\([a-z]\+\)[123]/\1X/g" "$$@"; }; \
	    dl --label cbc --label lp_solve \
	    <(bandx $(CBC_REPORT)) \
	    <(bandx $(LP_SOLVE_REPORT))'


##############################################################################
# targets shared by multiple solvers

# https://adirondackfirefly.wordpress.com/2012/04/12/makefiles-howto-threadsafe-mkdir/
%/$(DIR_EXISTS):
	touch $@

.PHONY: check
check: $(GMPL) $(GMPL_FILES) $(GMPL_STUDENT_SKILLS) $(DATA_DIR_EXISTS)
	glpsol $(GLPSOL_INPUTS) --check

$(CPLEX): $(GMPL) $(GMPL_FILES) $(GMPL_STUDENT_SKILLS) $(DATA_DIR_EXISTS)
	glpsol $(GLPSOL_INPUTS) --check --wlp $@
	wc -l $@


##############################################################################
# glpsol / glpk

.PHONY: glpsol
glpsol: $(GLPSOL_REPORT)

GLPSOL_SED_FIXUP = 's/, )/)/; s/, $$//; s/,)/)/g;'
$(GLPSOL_SOLUTION): $(GMPL) $(GMPL_FILES) $(GMPL_STUDENT_SKILLS) \
    Makefile $(SOLUTIONS_DIR_EXISTS) $(TIMINGS_DIR_EXISTS)
	time -o $(GLPSOL_TIMING) \
		glpsol $(GLPSOL_INPUTS) $(GLPSOL_SOLVE_OPTIONS) --output $@ | \
		sed $(GLPSOL_SED_FIXUP)
	# For use with --log $@
	#sed -i $(GLPSOL_SED_FIXUP) $@

$(GLPSOL_REPORT): $(GLPSOL_SOLUTION) Makefile report.py $(REPORTS_DIR_EXISTS)
	./report.py glpsol $< $(REPORT_ARGS) $(GLPSOL_TIMING) > $@
	cat $@


##############################################################################
# scip

.PHONY: scip
scip: $(SCIP_REPORT)

$(SCIP_SOLUTION): $(CPLEX) Makefile \
    $(SOLUTIONS_DIR_EXISTS) $(TIMINGS_DIR_EXISTS)
	rm -f $@
	time -o $(SCIP_TIMING) $(SCIP) -f $< -l $@

$(SCIP_REPORT): $(SCIP_SOLUTION) scip.set Makefile report.py \
    $(REPORTS_DIR_EXISTS)
	./report.py scip $< $(REPORT_ARGS) $(SCIP_TIMING) > $@
	cat $@


##############################################################################
# cbc

.PHONY: cbc
cbc: $(CBC_REPORT)

$(CBC_SOLUTION): $(CPLEX) Makefile \
    $(SOLUTIONS_DIR_EXISTS) $(TIMINGS_DIR_EXISTS)
	echo "limits/time = $(SOLVER_TIMEOUT)" > scip.set
	time -o $(CBC_TIMING) \
		 $(CBC) $< $(CBC_SOLVE_OPTIONS) solve solu $@

$(CBC_REPORT): $(CBC_SOLUTION) Makefile report.py \
    $(REPORTS_DIR_EXISTS)
	./report.py cbc $< $(REPORT_ARGS) $(CBC_TIMING) > $@
	cat $@


##############################################################################
# linting

pep8:
	pep8 --ignore=E221 *.py

##############################################################################
# cleaning

.PHONY: clean-lp_solve
clean-lp_solve:
	rm -f $(LP_SOLVE_TIMING) $(LP_SOLVE_SOLUTION) $(LP_SOLVE_REPORT)

.PHONY: clean-glpsol
clean-glpsol:
	rm -f $(GLPSOL_TIMING) $(GLPSOL_SOLUTION) $(GLPSOL_REPORT)

.PHONY: clean-scip
clean-scip:
	rm -f $(SCIP_TIMING) $(SCIP_SOLUTION) $(SCIP_REPORT)

.PHONY: clean-cbc
clean-cbc:
	rm -f $(CBC_TIMING) $(CBC_SOLUTION) $(CBC_REPORT)

.PHONY: clean
clean: clean-lp_solve clean-glpsol clean-scip clean-cbc
